### ISSUE TITLE
咨询：应用场景

### ISSUE THREAD

**Issue by zry656565** [JexCheng/ShunEncode#1]
请问这个 repo 有什么应用场景么？

**Comment by JexCheng** [comment]
可以用来在境内论坛上发帖包含敏感词又不会被机器自动屏蔽掉。

但是，其实，我只是弄了玩玩而已

**Comment by zry656565** [comment]
嗯，如果配上这么一个解码插件倒是有用。谢谢解惑哈

**Comment by xgqfrms-GitHub** [comment]
it is not useful at all!

> 在境内论坛上发帖讨论敏感内容又不会被机器自动屏蔽掉
敏感内容 are can't be read!
just like a => a+x0000;
             b => b+x0000;
